# Generated by Django 4.1.5 on 2023-01-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=123, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
