# Generated by Django 4.1.5 on 2023-01-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
