# Generated by Django 4.1.5 on 2023-01-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage_is_published_galleryimage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='exif_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True),
        ),
    ]
