# Generated by Django 4.1.5 on 2023-01-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_galleryimage_exif_data_alter_galleryimage_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='exif_data',
            new_name='location',
        ),
    ]
